### ISSUE TITLE
Crash Glass Panes

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#11]
There seems to be an odd bug affecting glass pane ctms, which causes the client to crash.

Deleting the ctm files and textures seems to fix the issue - obviously, this is not ideal if ctms are needed on these blocks!

**Comment by dags-** [comment]
This should be resolved before we update

**Comment by dags-** [comment]
Crash report (Note: `Block: minecraft:stained_glass[color=brown]`):
```
java.lang.ArrayIndexOutOfBoundsException: -65
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(SourceFile:58)
	at net.minecraft.block.BlockFence.func_176524_e(SourceFile:125)
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:41)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:878)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:853)
	at ConnectedTextures.getConnectedTextureHorizontal(ConnectedTextures.java:930)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:409)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:180)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:101)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:261)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:116)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:66)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:287)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(SourceFile:58)
	at net.minecraft.block.BlockFence.func_176524_e(SourceFile:125)
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:41)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:878)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:853)
	at ConnectedTextures.getConnectedTextureHorizontal(ConnectedTextures.java:930)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:409)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:180)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:101)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:261)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:116)

-- Block model being tesselated --
Details:
	Block: minecraft:stained_glass[color=brown]
	Block location: World: (2352,61,-370), Chunk: (at 0,3,14 in 147,-24; contains blocks 2352,0,-384 to 2367,255,-369), Region: (4,-1; contains chunks 128,-32 to 159,-1, blocks 2048,0,-512 to 2559,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:66)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:52)
```

**Comment by dags-** [comment]
Wheellee said he has removed the brown stained glass ctm, so this should be 'fixed' (worked-around) going forward

**Comment by dags-** [comment]
Keep open until changes are put up as a release on the resourcepack repo

**Comment by dags-** [comment]
OptiFix prevents the crash - not sure if it has an impact on whether the glass ctm still works or not
